### PR TITLE
Fix https://github.com/hax/refactor/issues/33

### PR DESCRIPTION
**Pull request by IceOnFire**
This should get rid of the annoying error message.

### CODE REVIEW

**Comment by kutsan** [comment]
Thank you!

**Comment by IceOnFire** [comment]
Thanks to @zaaack for the fix, I only applied it! @hax, could you please accept my PR?

**Comment by kutsan** [comment]
Sadly, I am not a maintainer. I wanted to say thanks because that dialog was annoying.

Also, thanks @zaaack 👍

**Comment by iamchenxin** [comment]
Hope this PR will be accepted sooner.

**Comment by IceOnFire** [comment]
Let's hope that @hax is ok, I'm starting to worry!

For those who need a quick and dirty solution, open your $HOME/.atom/packages/refactor/lib/watcher.coffee and in line 54 replace

```coffee
@ripper.dispose()
```

with

```coffee
@ripper.dispose?()
```

by just adding a `?`.

**Comment by iamchenxin** [comment]
... 囧, seems, @hax is participating in a party [zhihu lives](https://www.zhihu.com/lives/778991567569440768) for some days. Hope he will be back soon.
@IceOnFire He is ok ...

**Comment by IceOnFire** [comment]
Welcome back, and thanks for the merge! (^.^)

**Comment by hax** [comment]
Thank you guys :)  The new version has been published.

**Pull request merged**
